# Generated by Django 4.1.7 on 2023-02-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='ToDo',
        ),
    ]
